server:
  port: 8085

spring:
  application:
    name: auth-service

  config:
    import: 'optional:configserver:'

  cloud:
    config:
      uri: http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5432/auth-db
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 6

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: my-super-secret-key-for-jwt-signing-min-32-charsets
  access-token-expiration-ms: 900000

refresh-token:
  expiration-ms: 604800000
  max-tokens-per-user: 3

secret-key: my-hmac-secret-key-for-hashing-min-32-characters-long

security-config:
  permit-all:
    - /error
    - /v3/api-docs/**
    - /swagger-ui/**
    - /swagger-ui.html
    - /actuator/health
    - /actuator/info
    - /api/v1/auth/sign-up
    - /api/v1/sessions
    - /api/v1/tokens/refresh
  allowed-headers: ${SECURITY_ALLOWED_HEADERS:*}
  allowed-methods: ${SECURITY_ALLOWED_METHODS:GET,POST,PUT,DELETE,PATCH,OPTIONS}
  allowed-origins: ${SECURITY_ALLOWED_ORIGINS:http://localhost:3000}

app:
  security:
    password-regex: ^(?=.*\d)(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{8,24}$